export const portfolioData = {
  name: "Joy Saha",
  role: "Full Stack Developer & Digital Problem Solver",
  roles: [
    "Full Stack Developer",
    "Digital Problem Solver",
    "UI/UX Designer",
    "AI Integration Specialist",
    "WordPress Expert",
    "Creative Thinker",
    "Tech Enthusiast"
  ],
  tagline: "Building scalable, high-performance digital solutions with precision and passion.",
  about: "I am a passionate developer who enjoys turning innovative ideas into powerful digital products. I specialize in building modern, scalable, and high-performance web and application solutions that help businesses grow in the digital world.",
  skills: [
    { name: "Full Stack Web Development", level: 95, category: "Development", icon: "Globe" },
    { name: "Custom WordPress Development", level: 90, category: "Development", icon: "Layout" },
    { name: "Backend Systems (APIs & DB)", level: 92, category: "Backend", icon: "Database" },
    { name: "AI-powered Web Apps", level: 85, category: "AI", icon: "Zap" },
    { name: "Mobile App Development", level: 80, category: "Mobile", icon: "Smartphone" },
    { name: "Database Design & Optimization", level: 88, category: "Backend", icon: "Server" },
    { name: "Graphic & Presentation Design", level: 85, category: "Design", icon: "ImageIcon" },
    { name: "Content Writing", level: 80, category: "Content", icon: "PenTool" },
  ],
  services: [
    {
      title: "Full Stack Systems",
      description: "End-to-end architecture combining high-performance backends with fluid, artistic interfaces.",
      icon: "Layers",
    },
    {
      title: "AI Ecosystems",
      description: "Integrating advanced LLMs and neural architectures into your core business logic.",
      icon: "Zap",
    },
    {
      title: "Backend Core",
      description: "Securing your data with robust, distributed database systems and real-time API layers.",
      icon: "Database",
    },
    {
      title: "Creative Tech",
      description: "Custom platform solutions that merge high-concept design with flawless technical execution.",
      icon: "Sparkles",
    },
  ],
  projects: [
    {
      id: 1,
      title: "E-Commerce Titan",
      category: "Full Stack",
      image: "https://picsum.photos/seed/shop/800/600",
      description: "A high-performance e-commerce platform with real-time inventory and AI recommendations.",
      tech: ["React", "Node.js", "PostgreSQL", "Tailwind"],
      link: "#",
    },
    {
      id: 2,
      title: "AI Content Studio",
      category: "AI",
      image: "https://picsum.photos/seed/ai-studio/800/600",
      description: "An AI-powered platform for generating high-quality marketing content and images.",
      tech: ["Next.js", "Gemini API", "Firebase"],
      link: "#",
    },
    {
      id: 3,
      title: "HealthTrack Mobile",
      category: "Mobile",
      image: "https://picsum.photos/seed/health/800/600",
      description: "A comprehensive health and fitness tracking app with wearable integration.",
      tech: ["React Native", "Express", "MongoDB"],
      link: "#",
    },
    {
      id: 4,
      title: "Corporate Portal",
      category: "Backend",
      image: "https://picsum.photos/seed/corp/800/600",
      description: "Secure internal management system with advanced RBAC and audit logging.",
      tech: ["Go", "Vue.js", "Redis"],
      link: "#",
    },
  ],
  experience: [
    {
      year: "2022 - Present",
      role: "Senior Full Stack Developer",
      company: "TechInnovate Solutions",
      description: "Leading development of scalable SaaS products and mentoring junior developers.",
    },
    {
      year: "2020 - 2022",
      role: "Web Developer",
      company: "Digital Pulse Agency",
      description: "Developed custom WordPress themes and high-traffic marketing sites.",
    },
  ],
};
